language: node_js
node_js:
  - 6
  - 7
before_script:
  - npm install
script:
  - npm run make
  - npm run test
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/codeclimate-test-reporter'
branches:
  only:
    - master
addons:
  code_climate:
      repo_token: 403060cc0759da8ecd18d93116ecb6c0973c45a0cd90beb0f9611be45d30e2c4
